# Generated by Django 5.2 on 2025-05-01 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='document',
            name='recommended_documents',
            field=models.ManyToManyField(blank=True, null=True, to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
