# Generated by Django 5.2 on 2025-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_keywords_document_recommended_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='recommended_documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
    ]
